// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'97df15c0d2f9106b6248f371efae461ca22e973f4b966078ee9abc32bd44142a'>;
export type ExecutionHash =
  ExecutionHashBase<'7f2348ad8c218f3fbaba815baeede474a25bf837fa5ce6f0f94ec8922043e54f'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Carro: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly encontroId: CodecTypes['pg/text@1']['output'];
      readonly motorista: CodecTypes['pg/text@1']['output'];
      readonly origemEndereco: CodecTypes['pg/text@1']['output'];
      readonly origemCep: CodecTypes['pg/text@1']['output'] | null;
      readonly origemLat: CodecTypes['pg/float8@1']['output'] | null;
      readonly origemLng: CodecTypes['pg/float8@1']['output'] | null;
      readonly capacidade: CodecTypes['pg/int4@1']['output'];
      readonly distanciaKm: CodecTypes['pg/float8@1']['output'] | null;
      readonly tempoMin: CodecTypes['pg/float8@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Configuracao: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly encontroId: CodecTypes['pg/text@1']['output'];
      readonly pesoDistancia: CodecTypes['pg/float8@1']['output'];
      readonly pesoFila: CodecTypes['pg/float8@1']['output'];
      readonly pesoPresenca: CodecTypes['pg/float8@1']['output'];
      readonly pesoIndicacao: CodecTypes['pg/float8@1']['output'];
      readonly raioClusteringKm: CodecTypes['pg/float8@1']['output'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Encontrista: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly encontroId: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
      readonly endereco: CodecTypes['pg/text@1']['output'];
      readonly cep: CodecTypes['pg/text@1']['output'] | null;
      readonly lat: CodecTypes['pg/float8@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'] | null;
      readonly distanciaKm: CodecTypes['pg/float8@1']['output'] | null;
      readonly posicaoFila: CodecTypes['pg/int4@1']['output'] | null;
      readonly notaPresenca: CodecTypes['pg/int4@1']['output'];
      readonly notaIndicacao: CodecTypes['pg/int4@1']['output'];
      readonly status: 'INSCRITO' | 'CONFIRMADO' | 'FILA' | 'DESISTIU';
      readonly score: CodecTypes['pg/float8@1']['output'] | null;
      readonly prioridade: 'ALTA' | 'MEDIA' | 'BAIXA' | null;
      readonly carroId: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Encontro: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly paroquiaNome: CodecTypes['pg/text@1']['output'];
      readonly paroquiaLat: CodecTypes['pg/float8@1']['output'] | null;
      readonly paroquiaLng: CodecTypes['pg/float8@1']['output'] | null;
      readonly localNome: CodecTypes['pg/text@1']['output'];
      readonly localLat: CodecTypes['pg/float8@1']['output'] | null;
      readonly localLng: CodecTypes['pg/float8@1']['output'] | null;
      readonly vagasTotais: CodecTypes['pg/int4@1']['output'];
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Profile: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Carro: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly encontroId: CodecTypes['pg/text@1']['input'];
      readonly motorista: CodecTypes['pg/text@1']['input'];
      readonly origemEndereco: CodecTypes['pg/text@1']['input'];
      readonly origemCep: CodecTypes['pg/text@1']['input'] | null;
      readonly origemLat: CodecTypes['pg/float8@1']['input'] | null;
      readonly origemLng: CodecTypes['pg/float8@1']['input'] | null;
      readonly capacidade: CodecTypes['pg/int4@1']['input'];
      readonly distanciaKm: CodecTypes['pg/float8@1']['input'] | null;
      readonly tempoMin: CodecTypes['pg/float8@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Configuracao: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly encontroId: CodecTypes['pg/text@1']['input'];
      readonly pesoDistancia: CodecTypes['pg/float8@1']['input'];
      readonly pesoFila: CodecTypes['pg/float8@1']['input'];
      readonly pesoPresenca: CodecTypes['pg/float8@1']['input'];
      readonly pesoIndicacao: CodecTypes['pg/float8@1']['input'];
      readonly raioClusteringKm: CodecTypes['pg/float8@1']['input'];
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Encontrista: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly encontroId: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
      readonly endereco: CodecTypes['pg/text@1']['input'];
      readonly cep: CodecTypes['pg/text@1']['input'] | null;
      readonly lat: CodecTypes['pg/float8@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'] | null;
      readonly distanciaKm: CodecTypes['pg/float8@1']['input'] | null;
      readonly posicaoFila: CodecTypes['pg/int4@1']['input'] | null;
      readonly notaPresenca: CodecTypes['pg/int4@1']['input'];
      readonly notaIndicacao: CodecTypes['pg/int4@1']['input'];
      readonly status: 'INSCRITO' | 'CONFIRMADO' | 'FILA' | 'DESISTIU';
      readonly score: CodecTypes['pg/float8@1']['input'] | null;
      readonly prioridade: 'ALTA' | 'MEDIA' | 'BAIXA' | null;
      readonly carroId: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Encontro: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly paroquiaNome: CodecTypes['pg/text@1']['input'];
      readonly paroquiaLat: CodecTypes['pg/float8@1']['input'] | null;
      readonly paroquiaLng: CodecTypes['pg/float8@1']['input'] | null;
      readonly localNome: CodecTypes['pg/text@1']['input'];
      readonly localLat: CodecTypes['pg/float8@1']['input'] | null;
      readonly localLng: CodecTypes['pg/float8@1']['input'] | null;
      readonly vagasTotais: CodecTypes['pg/int4@1']['input'];
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Profile: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly carro: {
      readonly capacidade: CodecTypes['pg/int4@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly distanciaKm: CodecTypes['pg/float8@1']['output'] | null;
      readonly encontroId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly motorista: CodecTypes['pg/text@1']['output'];
      readonly origemCep: CodecTypes['pg/text@1']['output'] | null;
      readonly origemEndereco: CodecTypes['pg/text@1']['output'];
      readonly origemLat: CodecTypes['pg/float8@1']['output'] | null;
      readonly origemLng: CodecTypes['pg/float8@1']['output'] | null;
      readonly tempoMin: CodecTypes['pg/float8@1']['output'] | null;
    };
    readonly configuracao: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly encontroId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly pesoDistancia: CodecTypes['pg/float8@1']['output'];
      readonly pesoFila: CodecTypes['pg/float8@1']['output'];
      readonly pesoIndicacao: CodecTypes['pg/float8@1']['output'];
      readonly pesoPresenca: CodecTypes['pg/float8@1']['output'];
      readonly raioClusteringKm: CodecTypes['pg/float8@1']['output'];
    };
    readonly encontrista: {
      readonly carroId: CodecTypes['pg/text@1']['output'] | null;
      readonly cep: CodecTypes['pg/text@1']['output'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly distanciaKm: CodecTypes['pg/float8@1']['output'] | null;
      readonly encontroId: CodecTypes['pg/text@1']['output'];
      readonly endereco: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lat: CodecTypes['pg/float8@1']['output'] | null;
      readonly lng: CodecTypes['pg/float8@1']['output'] | null;
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly notaIndicacao: CodecTypes['pg/int4@1']['output'];
      readonly notaPresenca: CodecTypes['pg/int4@1']['output'];
      readonly posicaoFila: CodecTypes['pg/int4@1']['output'] | null;
      readonly prioridade: 'ALTA' | 'MEDIA' | 'BAIXA' | null;
      readonly score: CodecTypes['pg/float8@1']['output'] | null;
      readonly status: 'INSCRITO' | 'CONFIRMADO' | 'FILA' | 'DESISTIU';
      readonly telefone: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly encontro: {
      readonly ativo: CodecTypes['pg/bool@1']['output'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly localLat: CodecTypes['pg/float8@1']['output'] | null;
      readonly localLng: CodecTypes['pg/float8@1']['output'] | null;
      readonly localNome: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly paroquiaLat: CodecTypes['pg/float8@1']['output'] | null;
      readonly paroquiaLng: CodecTypes['pg/float8@1']['output'] | null;
      readonly paroquiaNome: CodecTypes['pg/text@1']['output'];
      readonly vagasTotais: CodecTypes['pg/int4@1']['output'];
    };
    readonly profile: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly nome: CodecTypes['pg/text@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly carro: {
      readonly capacidade: CodecTypes['pg/int4@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly distanciaKm: CodecTypes['pg/float8@1']['input'] | null;
      readonly encontroId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly motorista: CodecTypes['pg/text@1']['input'];
      readonly origemCep: CodecTypes['pg/text@1']['input'] | null;
      readonly origemEndereco: CodecTypes['pg/text@1']['input'];
      readonly origemLat: CodecTypes['pg/float8@1']['input'] | null;
      readonly origemLng: CodecTypes['pg/float8@1']['input'] | null;
      readonly tempoMin: CodecTypes['pg/float8@1']['input'] | null;
    };
    readonly configuracao: {
      readonly atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly encontroId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly pesoDistancia: CodecTypes['pg/float8@1']['input'];
      readonly pesoFila: CodecTypes['pg/float8@1']['input'];
      readonly pesoIndicacao: CodecTypes['pg/float8@1']['input'];
      readonly pesoPresenca: CodecTypes['pg/float8@1']['input'];
      readonly raioClusteringKm: CodecTypes['pg/float8@1']['input'];
    };
    readonly encontrista: {
      readonly carroId: CodecTypes['pg/text@1']['input'] | null;
      readonly cep: CodecTypes['pg/text@1']['input'] | null;
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly distanciaKm: CodecTypes['pg/float8@1']['input'] | null;
      readonly encontroId: CodecTypes['pg/text@1']['input'];
      readonly endereco: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lat: CodecTypes['pg/float8@1']['input'] | null;
      readonly lng: CodecTypes['pg/float8@1']['input'] | null;
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly notaIndicacao: CodecTypes['pg/int4@1']['input'];
      readonly notaPresenca: CodecTypes['pg/int4@1']['input'];
      readonly posicaoFila: CodecTypes['pg/int4@1']['input'] | null;
      readonly prioridade: 'ALTA' | 'MEDIA' | 'BAIXA' | null;
      readonly score: CodecTypes['pg/float8@1']['input'] | null;
      readonly status: 'INSCRITO' | 'CONFIRMADO' | 'FILA' | 'DESISTIU';
      readonly telefone: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly encontro: {
      readonly ativo: CodecTypes['pg/bool@1']['input'];
      readonly criadoEm: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly data: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly localLat: CodecTypes['pg/float8@1']['input'] | null;
      readonly localLng: CodecTypes['pg/float8@1']['input'] | null;
      readonly localNome: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly paroquiaLat: CodecTypes['pg/float8@1']['input'] | null;
      readonly paroquiaLng: CodecTypes['pg/float8@1']['input'] | null;
      readonly paroquiaNome: CodecTypes['pg/text@1']['input'];
      readonly vagasTotais: CodecTypes['pg/int4@1']['input'];
    };
    readonly profile: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly nome: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Profile = {
    id: CodecTypes['pg/text@1']['output'];
    userId: CodecTypes['pg/text@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    role: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Encontro = {
    id: CodecTypes['pg/text@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    data: CodecTypes['pg/timestamptz-temporal@1']['output'];
    paroquiaNome: CodecTypes['pg/text@1']['output'];
    paroquiaLat: CodecTypes['pg/float8@1']['output'] | null;
    paroquiaLng: CodecTypes['pg/float8@1']['output'] | null;
    localNome: CodecTypes['pg/text@1']['output'];
    localLat: CodecTypes['pg/float8@1']['output'] | null;
    localLng: CodecTypes['pg/float8@1']['output'] | null;
    vagasTotais: CodecTypes['pg/int4@1']['output'];
    ativo: CodecTypes['pg/bool@1']['output'];
    criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    carros: public_Carro[];
    configuracao: public_Configuracao | null;
    encontristas: public_Encontrista[];
    readonly [RelationKeys]?: 'carros' | 'configuracao' | 'encontristas';
  };
  export type public_Configuracao = {
    id: CodecTypes['pg/text@1']['output'];
    encontroId: CodecTypes['pg/text@1']['output'];
    pesoDistancia: CodecTypes['pg/float8@1']['output'];
    pesoFila: CodecTypes['pg/float8@1']['output'];
    pesoPresenca: CodecTypes['pg/float8@1']['output'];
    pesoIndicacao: CodecTypes['pg/float8@1']['output'];
    raioClusteringKm: CodecTypes['pg/float8@1']['output'];
    atualizadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    encontro: public_Encontro;
    readonly [RelationKeys]?: 'encontro';
  };
  export type public_Encontrista = {
    id: CodecTypes['pg/text@1']['output'];
    encontroId: CodecTypes['pg/text@1']['output'];
    nome: CodecTypes['pg/text@1']['output'];
    telefone: CodecTypes['pg/text@1']['output'] | null;
    endereco: CodecTypes['pg/text@1']['output'];
    cep: CodecTypes['pg/text@1']['output'] | null;
    lat: CodecTypes['pg/float8@1']['output'] | null;
    lng: CodecTypes['pg/float8@1']['output'] | null;
    distanciaKm: CodecTypes['pg/float8@1']['output'] | null;
    posicaoFila: CodecTypes['pg/int4@1']['output'] | null;
    notaPresenca: CodecTypes['pg/int4@1']['output'];
    notaIndicacao: CodecTypes['pg/int4@1']['output'];
    status: 'INSCRITO' | 'CONFIRMADO' | 'FILA' | 'DESISTIU';
    score: CodecTypes['pg/float8@1']['output'] | null;
    prioridade: 'ALTA' | 'MEDIA' | 'BAIXA' | null;
    carroId: CodecTypes['pg/text@1']['output'] | null;
    criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    carro: public_Carro | null;
    encontro: public_Encontro;
    readonly [RelationKeys]?: 'carro' | 'encontro';
  };
  export type public_Carro = {
    id: CodecTypes['pg/text@1']['output'];
    encontroId: CodecTypes['pg/text@1']['output'];
    motorista: CodecTypes['pg/text@1']['output'];
    origemEndereco: CodecTypes['pg/text@1']['output'];
    origemCep: CodecTypes['pg/text@1']['output'] | null;
    origemLat: CodecTypes['pg/float8@1']['output'] | null;
    origemLng: CodecTypes['pg/float8@1']['output'] | null;
    capacidade: CodecTypes['pg/int4@1']['output'];
    distanciaKm: CodecTypes['pg/float8@1']['output'] | null;
    tempoMin: CodecTypes['pg/float8@1']['output'] | null;
    criadoEm: CodecTypes['pg/timestamptz-temporal@1']['output'];
    encontristas: public_Encontrista[];
    encontro: public_Encontro;
    readonly [RelationKeys]?: 'encontristas' | 'encontro';
  };
}

export declare const models: {
  public: {
    Profile: Models.public_Profile;
    Encontro: Models.public_Encontro;
    Configuracao: Models.public_Configuracao;
    Encontrista: Models.public_Encontrista;
    Carro: Models.public_Carro;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly carro: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly encontroId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly motorista: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly origemEndereco: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly origemCep: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly origemLat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly origemLng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly capacidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 3>;
                  };
                };
                readonly distanciaKm: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly tempoMin: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'carro_encontroId_idx_5986ca36';
                  readonly prefix: 'carro_encontroId_idx';
                  readonly columns: readonly ['encontroId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'carro';
                    readonly columns: readonly ['encontroId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'encontro';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly configuracao: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly encontroId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pesoDistancia: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 1>;
                  };
                };
                readonly pesoFila: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 1>;
                  };
                };
                readonly pesoPresenca: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 1>;
                  };
                };
                readonly pesoIndicacao: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 1>;
                  };
                };
                readonly raioClusteringKm: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 1.5>;
                  };
                };
                readonly atualizadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['encontroId'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'configuracao';
                    readonly columns: readonly ['encontroId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'encontro';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly encontrista: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly encontroId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly telefone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly endereco: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly cep: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly lat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly lng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly distanciaKm: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly posicaoFila: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly notaPresenca: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 5>;
                  };
                };
                readonly notaIndicacao: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 5>;
                  };
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'INSCRITO'>;
                  };
                };
                readonly score: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly prioridade: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly carroId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'encontrista_encontroId_idx_5986ca36';
                  readonly prefix: 'encontrista_encontroId_idx';
                  readonly columns: readonly ['encontroId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'encontrista_carroId_idx_3d3e8554';
                  readonly prefix: 'encontrista_carroId_idx';
                  readonly columns: readonly ['carroId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'encontrista';
                    readonly columns: readonly ['encontroId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'encontro';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'encontrista';
                    readonly columns: readonly ['carroId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'carro';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly encontro: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly data: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly paroquiaNome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly paroquiaLat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly paroquiaLng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly localNome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly localLat: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly localLng: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly vagasTotais: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 30>;
                  };
                };
                readonly ativo: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly criadoEm: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly profile: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly nome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'equipe'>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly Prioridade: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ALTA', 'MEDIA', 'BAIXA'];
            };
            readonly Status: {
              readonly kind: 'valueSet';
              readonly values: readonly ['INSCRITO', 'CONFIRMADO', 'FILA', 'DESISTIU'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly profile: { readonly namespace: 'public' & NamespaceId; readonly model: 'Profile' };
    readonly encontro: { readonly namespace: 'public' & NamespaceId; readonly model: 'Encontro' };
    readonly configuracao: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Configuracao';
    };
    readonly encontrista: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Encontrista';
    };
    readonly carro: { readonly namespace: 'public' & NamespaceId; readonly model: 'Carro' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Carro: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly encontroId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly motorista: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly origemEndereco: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly origemCep: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly origemLat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly origemLng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly capacidade: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly distanciaKm: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly tempoMin: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly encontristas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Encontrista';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['carroId'];
                };
              };
              readonly encontro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Encontro';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['encontroId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'carro';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly encontroId: { readonly column: 'encontroId' };
                readonly motorista: { readonly column: 'motorista' };
                readonly origemEndereco: { readonly column: 'origemEndereco' };
                readonly origemCep: { readonly column: 'origemCep' };
                readonly origemLat: { readonly column: 'origemLat' };
                readonly origemLng: { readonly column: 'origemLng' };
                readonly capacidade: { readonly column: 'capacidade' };
                readonly distanciaKm: { readonly column: 'distanciaKm' };
                readonly tempoMin: { readonly column: 'tempoMin' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Configuracao: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly encontroId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pesoDistancia: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly pesoFila: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly pesoPresenca: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly pesoIndicacao: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly raioClusteringKm: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly atualizadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly encontro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Encontro';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['encontroId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'configuracao';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly encontroId: { readonly column: 'encontroId' };
                readonly pesoDistancia: { readonly column: 'pesoDistancia' };
                readonly pesoFila: { readonly column: 'pesoFila' };
                readonly pesoPresenca: { readonly column: 'pesoPresenca' };
                readonly pesoIndicacao: { readonly column: 'pesoIndicacao' };
                readonly raioClusteringKm: { readonly column: 'raioClusteringKm' };
                readonly atualizadoEm: { readonly column: 'atualizadoEm' };
              };
            };
          };
          readonly Encontrista: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly encontroId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly telefone: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly endereco: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly cep: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly lng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly distanciaKm: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly posicaoFila: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly notaPresenca: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly notaIndicacao: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly score: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly prioridade: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly carroId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly carro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Carro';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['carroId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly encontro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Encontro';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['encontroId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'encontrista';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly encontroId: { readonly column: 'encontroId' };
                readonly nome: { readonly column: 'nome' };
                readonly telefone: { readonly column: 'telefone' };
                readonly endereco: { readonly column: 'endereco' };
                readonly cep: { readonly column: 'cep' };
                readonly lat: { readonly column: 'lat' };
                readonly lng: { readonly column: 'lng' };
                readonly distanciaKm: { readonly column: 'distanciaKm' };
                readonly posicaoFila: { readonly column: 'posicaoFila' };
                readonly notaPresenca: { readonly column: 'notaPresenca' };
                readonly notaIndicacao: { readonly column: 'notaIndicacao' };
                readonly status: { readonly column: 'status' };
                readonly score: { readonly column: 'score' };
                readonly prioridade: { readonly column: 'prioridade' };
                readonly carroId: { readonly column: 'carroId' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Encontro: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly data: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly paroquiaNome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paroquiaLat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly paroquiaLng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly localNome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly localLat: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly localLng: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly vagasTotais: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly ativo: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly criadoEm: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly carros: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Carro';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['encontroId'];
                };
              };
              readonly configuracao: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Configuracao';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['encontroId'];
                };
              };
              readonly encontristas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Encontrista';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['encontroId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'encontro';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nome: { readonly column: 'nome' };
                readonly data: { readonly column: 'data' };
                readonly paroquiaNome: { readonly column: 'paroquiaNome' };
                readonly paroquiaLat: { readonly column: 'paroquiaLat' };
                readonly paroquiaLng: { readonly column: 'paroquiaLng' };
                readonly localNome: { readonly column: 'localNome' };
                readonly localLat: { readonly column: 'localLat' };
                readonly localLng: { readonly column: 'localLng' };
                readonly vagasTotais: { readonly column: 'vagasTotais' };
                readonly ativo: { readonly column: 'ativo' };
                readonly criadoEm: { readonly column: 'criadoEm' };
              };
            };
          };
          readonly Profile: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'profile';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly nome: { readonly column: 'nome' };
                readonly email: { readonly column: 'email' };
                readonly role: { readonly column: 'role' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly Status: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'INSCRITO'; readonly value: 'INSCRITO' },
              { readonly name: 'CONFIRMADO'; readonly value: 'CONFIRMADO' },
              { readonly name: 'FILA'; readonly value: 'FILA' },
              { readonly name: 'DESISTIU'; readonly value: 'DESISTIU' },
            ];
          };
          readonly Prioridade: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ALTA'; readonly value: 'ALTA' },
              { readonly name: 'MEDIA'; readonly value: 'MEDIA' },
              { readonly name: 'BAIXA'; readonly value: 'BAIXA' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'carro';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'configuracao';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'encontrista';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'encontro';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'profile';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
